// Updated Declarative Jenkinsfile: cross-platform (Windows/Unix), runs Maven build/tests, archives artifacts, and publishes TestNG/Extent reports
pipeline {
    agent any

    options {
        // keep 10 builds
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timestamps()
        ansiColor('xterm')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'mvn -B -DskipTests=false clean test'
                    } else {
                        // Windows (cmd.exe)
                        bat 'mvn -B -DskipTests=false clean test'
                    }
                }
            }
            post {
                always {
                    // Publish test results generated by Surefire (JUnit-style XMLs)
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Package') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'mvn -B -DskipTests=true package'
                    } else {
                        bat 'mvn -B -DskipTests=true package'
                    }
                }
            }
        }

        stage('Archive') {
            steps {
                // Archive common artifacts and test-output contents
                archiveArtifacts artifacts: 'target/*.jar, target/*.war, target/**/*.zip, test-output/**', fingerprint: true
            }
        }

        stage('Publish Reports') {
            steps {
                // publish HTML reports (ExtentReports, TestNG emailable report) if present
                script {
                    // Publish ExtentReport (commonly located under test-output/extent-report or target/extent-report)
                    def extentDirs = ['test-output/extent-report', 'target/extent-report', 'test-output/ExtentReports']
                    def published = false
                    for (d in extentDirs) {
                        if (fileExists(d + '/index.html')) {
                            publishHTML([allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true, reportDir: d, reportFiles: 'index.html', reportName: "Extent Report (${d})"]) 
                            published = true
                            break
                        }
                    }
                    if (!published) {
                        echo 'No Extent HTML report found to publish (expected index.html under common locations).'
                    }

                    // Publish TestNG emailable report if present
                    if (fileExists('test-output/emailable-report.html')) {
                        publishHTML([allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true, reportDir: 'test-output', reportFiles: 'emailable-report.html', reportName: 'TestNG Emailable Report'])
                    } else {
                        echo 'No TestNG emailable-report.html found under test-output/'.
                    }

                    // Attempt to publish TestNG structured results if plugin is installed
                    try {
                        publishTestNGResults testNGResultsPattern: 'test-output/testng-results.xml'
                    } catch (err) {
                        echo 'publishTestNGResults step is not available on this Jenkins (plugin missing) or failed: ' + err.toString()
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Collecting final artifacts and logs..."
            // Ensure TestNG/Surefire XMLs are archived too
            archiveArtifacts artifacts: 'target/surefire-reports/*.xml, test-output/**', fingerprint: true, allowEmptyArchive: true
        }

        success {
            echo 'Build succeeded'
        }

        failure {
            echo 'Build failed'
        }
    }
}